/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Recommendation } from "./Recommendation";
import { RecommendationCountArgs } from "./RecommendationCountArgs";
import { RecommendationFindManyArgs } from "./RecommendationFindManyArgs";
import { RecommendationFindUniqueArgs } from "./RecommendationFindUniqueArgs";
import { CreateRecommendationArgs } from "./CreateRecommendationArgs";
import { UpdateRecommendationArgs } from "./UpdateRecommendationArgs";
import { DeleteRecommendationArgs } from "./DeleteRecommendationArgs";
import { Post } from "../../post/base/Post";
import { RecommendationService } from "../recommendation.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Recommendation)
export class RecommendationResolverBase {
  constructor(
    protected readonly service: RecommendationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Recommendation",
    action: "read",
    possession: "any",
  })
  async _recommendationsMeta(
    @graphql.Args() args: RecommendationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Recommendation])
  @nestAccessControl.UseRoles({
    resource: "Recommendation",
    action: "read",
    possession: "any",
  })
  async recommendations(
    @graphql.Args() args: RecommendationFindManyArgs
  ): Promise<Recommendation[]> {
    return this.service.recommendations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Recommendation, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Recommendation",
    action: "read",
    possession: "own",
  })
  async recommendation(
    @graphql.Args() args: RecommendationFindUniqueArgs
  ): Promise<Recommendation | null> {
    const result = await this.service.recommendation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Recommendation)
  @nestAccessControl.UseRoles({
    resource: "Recommendation",
    action: "create",
    possession: "any",
  })
  async createRecommendation(
    @graphql.Args() args: CreateRecommendationArgs
  ): Promise<Recommendation> {
    return await this.service.createRecommendation({
      ...args,
      data: {
        ...args.data,

        post: args.data.post
          ? {
              connect: args.data.post,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Recommendation)
  @nestAccessControl.UseRoles({
    resource: "Recommendation",
    action: "update",
    possession: "any",
  })
  async updateRecommendation(
    @graphql.Args() args: UpdateRecommendationArgs
  ): Promise<Recommendation | null> {
    try {
      return await this.service.updateRecommendation({
        ...args,
        data: {
          ...args.data,

          post: args.data.post
            ? {
                connect: args.data.post,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Recommendation)
  @nestAccessControl.UseRoles({
    resource: "Recommendation",
    action: "delete",
    possession: "any",
  })
  async deleteRecommendation(
    @graphql.Args() args: DeleteRecommendationArgs
  ): Promise<Recommendation | null> {
    try {
      return await this.service.deleteRecommendation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Post, {
    nullable: true,
    name: "post",
  })
  @nestAccessControl.UseRoles({
    resource: "Post",
    action: "read",
    possession: "any",
  })
  async getPost(
    @graphql.Parent() parent: Recommendation
  ): Promise<Post | null> {
    const result = await this.service.getPost(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
