/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RecommendationService } from "../recommendation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RecommendationCreateInput } from "./RecommendationCreateInput";
import { Recommendation } from "./Recommendation";
import { Post } from "../../post/base/Post";
import { RecommendationFindManyArgs } from "./RecommendationFindManyArgs";
import { RecommendationWhereUniqueInput } from "./RecommendationWhereUniqueInput";
import { RecommendationUpdateInput } from "./RecommendationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RecommendationControllerBase {
  constructor(
    protected readonly service: RecommendationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Recommendation })
  @nestAccessControl.UseRoles({
    resource: "Recommendation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRecommendation(
    @common.Body() data: RecommendationCreateInput
  ): Promise<Recommendation> {
    return await this.service.createRecommendation({
      data: {
        ...data,

        post: data.post
          ? {
              connect: data.post,
            }
          : undefined,
      },
      select: {
        comments: true,
        createdAt: true,
        id: true,

        post: {
          select: {
            id: true,
          },
        },

        rating: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Recommendation] })
  @ApiNestedQuery(RecommendationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Recommendation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async recommendations(
    @common.Req() request: Request
  ): Promise<Recommendation[]> {
    const args = plainToClass(RecommendationFindManyArgs, request.query);
    return this.service.recommendations({
      ...args,
      select: {
        comments: true,
        createdAt: true,
        id: true,

        post: {
          select: {
            id: true,
          },
        },

        rating: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Recommendation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Recommendation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async recommendation(
    @common.Param() params: RecommendationWhereUniqueInput
  ): Promise<Recommendation | null> {
    const result = await this.service.recommendation({
      where: params,
      select: {
        comments: true,
        createdAt: true,
        id: true,

        post: {
          select: {
            id: true,
          },
        },

        rating: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Recommendation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Recommendation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRecommendation(
    @common.Param() params: RecommendationWhereUniqueInput,
    @common.Body() data: RecommendationUpdateInput
  ): Promise<Recommendation | null> {
    try {
      return await this.service.updateRecommendation({
        where: params,
        data: {
          ...data,

          post: data.post
            ? {
                connect: data.post,
              }
            : undefined,
        },
        select: {
          comments: true,
          createdAt: true,
          id: true,

          post: {
            select: {
              id: true,
            },
          },

          rating: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Recommendation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Recommendation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRecommendation(
    @common.Param() params: RecommendationWhereUniqueInput
  ): Promise<Recommendation | null> {
    try {
      return await this.service.deleteRecommendation({
        where: params,
        select: {
          comments: true,
          createdAt: true,
          id: true,

          post: {
            select: {
              id: true,
            },
          },

          rating: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
